### ISSUE TITLE
Serve the registration page

### ISSUE THREAD

**Issue by illegalprime** [HackGT/registration#1]
Assume you have a JSON object with the configuration for the registration page is a format similar to:
```YAML
questions:
  - type: text
    text: What's good?

  - type: select
    text: 'Dietary Restrictions:'
    options:
      - Vegan
      - Vegetarian
      - Kosher
      - Paleo
```

Use this configuration to render and cache a handlebars template that is the HTML of the registration page. Finally add a route that serves this cached page.
