### ISSUE TITLE
Record the responses in Mongo

### ISSUE THREAD

**Issue by illegalprime** [HackGT/registration#2]
Assume that you have a JSON configuration of the registration questions equivalent to the config used in #1 , like so:
```YAML
questions:
  - type: text
    text: What's good?

  - type: select
    text: 'Dietary Restrictions:'
    options:
      - Vegan
      - Vegetarian
      - Kosher
      - Paleo
```

Use this configuration to make a schema for mongo at startup and connect to mongo.

Create a route that will accept the HTML form input, verify it against the schema, and store it in mongo.

Return a success page in the event the data is successfully recorded into mongo.
Return a failure if this procedure encounters a fatal error.
