### ISSUE TITLE
Client-side validation

### ISSUE THREAD

**Issue by illegalprime** [HackGT/registration#5]
The configuration file for the questions could have some restrictions, or could require preprocessing (such as when uploading a resume maybe it gets sent to an S3 bucket or maybe its just converted to `base64`). This will be the same format as in #1 and #2 :

```YAML
questions:
  - type: text
    pattern: [0-9]{10}
    text: Phone #

  - type: file
    text: Resume
    size-limit: 1kb
```

Since each type of question will likely have its own validation parameters, simply start with validating text with a regex and displaying UI feedback to the user, disallowing submission if the input is invalid.
